"""Trace real reviews through every stage from saved artifacts only (no model calls).

One review: source row -> enrichment call and validated record -> verification -> issue membership ->
baseline ranking -> memo claims. Plus one ambiguous case (verifier disagreement) and one failed-output case
(an invalid model row that code rejected and retried), with the recorded handling decision.
"""

from __future__ import annotations

import csv
import hashlib
import json
from pathlib import Path

from .orchestrator import load_records


def _csv(path: Path) -> list[dict]:
    with path.open(encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def _jsonl(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def _call(store, request_id: str | None) -> dict | None:
    if not request_id:
        return None
    r = store.one("SELECT * FROM calls WHERE request_id=?", (request_id,))
    return dict(r) if r else None


def _pick(seed: str, ids: list[str]) -> str | None:
    return min(ids, key=lambda i: hashlib.sha256(f"{seed}:{i}".encode()).hexdigest()) if ids else None


def _fence(obj) -> str:
    return "```json\n" + json.dumps(obj, ensure_ascii=False, indent=2) + "\n```"


def build_trace(ctx) -> str:
    run_dir = ctx.run_dir
    recs = {r["review_id"]: r for r in load_records(ctx)}
    input_sha = ctx.store.scalar("SELECT input_sha FROM runs WHERE run_id=?", (ctx.run_id,))
    for row in ctx.store.q("SELECT r.review_id, s.review_text FROM records r JOIN rows s ON s.input_sha=? "
                           "AND s.idx=r.idx WHERE r.run_id=?", (input_sha, ctx.run_id)):
        recs[row["review_id"]]["review_text"] = row["review_text"]
    membership = _csv(run_dir / "membership.csv")
    issue_of = {m["review_id"]: m["issue_id"] for m in membership}
    ranking = {r["issue_id"]: r for r in _csv(run_dir / "ranking.csv")}
    claims = _csv(run_dir / "claims.csv")
    checks = json.loads((run_dir / "memo_checks.json").read_text())
    verify = {v["review_id"]: v for v in _jsonl(run_dir / "verify" / "verifier_predictions.jsonl")}
    memo = (run_dir / "memo.md").read_text(encoding="utf-8")
    claimed = list(dict.fromkeys(c["issue_id"] for c in claims))
    pack = set(checks.get("evidence_review_ids") or [])

    chosen, why = None, ""
    for iid in claimed:
        members = [rid for rid, i in issue_of.items() if i == iid]
        for pool, reason in ((sorted(set(members) & pack & set(verify)), "in the memo evidence pack and the verifier sample"),
                             (sorted(set(members) & pack), "in the memo evidence pack"),
                             (sorted(set(members) & set(verify)), "in the verifier sample")):
            chosen = _pick("trace-v1", pool)
            if chosen:
                why = f"member of `{iid}` (cited by memo claims), {reason}"
                break
        if chosen:
            break
    L = [f"# Traces for run `{ctx.run_id}`\n",
         "Generated by `python -m pipeline trace` from saved artifacts only (state database, `runs/` files); "
         "no model was called. Selection is deterministic (lowest SHA-256 of `trace-v1:` + review_id).\n"]
    if chosen:
        r = recs[chosen]
        call = _call(ctx.store, r.get("source_request_id"))
        rank = ranking[issue_of[chosen]]
        v = verify.get(chosen)
        L += [f"## 1. One review, end to end\n\nReview `{chosen}` was chosen because it is the {why}.\n",
              "**Source row (unchanged strings; contract row hash):**\n",
              _fence({"review_id": chosen, "review_text": r["review_text"], "review_rating": r["review_rating"],
                      "review_timestamp": r["review_timestamp"], "app_version": r["app_version"],
                      "source_sha256": r["source_sha256"]}),
              "\n**Enrichment** (model labels, validated by code; the quote is an exact source substring):\n",
              _fence({k: r.get(k) for k in ("status", "topic", "subtopic", "intent", "severity", "sentiment",
                                            "evidence_quote", "entities", "needs_review", "review_reason",
                                            "quote_method", "rule_adjustments", "label_config", "result_source",
                                            "cache_source_id", "source_request_id")}),
              "\n**The enrichment call that produced it:**\n",
              _fence({k: call[k] for k in ("request_id", "run_id", "role", "phase", "model", "n_items", "attempt",
                                           "outcome", "input_tokens", "cache_read_input_tokens", "output_tokens",
                                           "cost_usd", "duration_s")} if call else "call not found"),
              f"\nThe call carried {call['n_items'] if call else '?'} distinct texts (limit 50); code mapped row "
              "keys back to source IDs and rejected any misnumbered row.\n",
              "**Verification** (separate prompt, never shown the enrichment):\n",
              _fence({k: v[k] for k in ("verify_topic", "verify_intent", "verify_severity", "topic_match",
                                        "intent_match", "severity_abs_diff", "disagreement")} if v
                     else "not in the seeded verification sample"),
              f"\n**Issue membership** (code: issue = subtopic): `{issue_of[chosen]}` in `membership.csv`.\n",
              "**Baseline ranking row** (`ranking.csv`, priority = complaint_count × mean_severity = severity_sum):\n",
              _fence(rank),
              "\n**Memo claims about this issue** (`claims.csv`; the checker recomputes each value):\n",
              _fence([c for c in claims if c["issue_id"] == issue_of[chosen]])]
        lines = [ln for ln in memo.splitlines() if f"`{issue_of[chosen]}`" in ln]
        if lines:
            L += ["\n**Memo sentence citing it:**\n", "> " + lines[0].strip()[:900] + "\n"]
    dis = sorted(rid for rid, v in verify.items() if v.get("disagreement") and rid in issue_of)
    rid = _pick("trace-v1", dis)
    if rid:
        r, v = recs[rid], verify[rid]
        L += ["\n## 2. Ambiguous case: verifier disagreement\n",
              _fence({"review_id": rid, "review_text": r["review_text"],
                      "enrichment": {k: r[k] for k in ("topic", "subtopic", "intent", "severity", "needs_review",
                                                       "review_reason")},
                      "verifier": {k: v[k] for k in ("verify_topic", "verify_intent", "verify_severity")}}),
              "\n**Handling decision:** the verifier measures agreement; it never overrides labels. The record keeps "
              "its enrichment label, stays in its issue and the ranking, and is listed in "
              "`verify/disagreements.csv`. Disagreement rates are reported with the results so readers can judge "
              "label error.\n"]
    events = [json.loads(line) for line in (run_dir / "run_log.jsonl").read_text().splitlines() if '"invalid_output"' in line]
    ev = next((e for e in events if e.get("invalid_items")), None)
    if ev:
        first = _call(ctx.store, ev["request_id"])
        sent = json.loads(first["review_ids"]) if first else []
        rejected = [rid for rid in sent if rid in recs and recs[rid].get("source_request_id") != ev["request_id"]]
        outcomes = []
        for rid in rejected[:3]:
            c = _call(ctx.store, recs[rid].get("source_request_id"))
            outcomes.append({"review_id": rid, "final_status": recs[rid]["status"], "reason": recs[rid].get("reason"),
                             "completed_by": c and {k: c[k] for k in ("request_id", "invocation", "phase", "attempt",
                                                                       "n_items")}})
        L += ["\n## 3. Failed model output: rejected, then completed later\n",
              _fence({"invalid_output_event": ev,
                      "original_call": {k: first[k] for k in ("request_id", "n_items", "attempt", "outcome")} if first else None,
                      "rejected_items_found": len(rejected), "what_happened_to_them (first 3)": outcomes}),
              "\n**Handling decision:** code kept the valid rows of that response and rejected the invalid ones "
              "(wrong key position, or missing or invalid fields). Rejected items stay `pending` with nothing saved for "
              "them. The run re-sends them once (in smaller requests, attempt 2), then through the capped "
              "single-review fallback, and only then quarantines them with a reason and attempt count. The "
              "`completed_by` entries above show the call that actually completed each one. A `resume` phase means "
              "the run was interrupted before its retry queue reached them, and the resumed run labeled them as "
              "ordinary pending work. Nothing is silently dropped.\n"]
    quarantined = [r for r in recs.values() if r["status"] == "quarantined"]
    reasons = sorted({r["reason"] for r in quarantined})
    L += [f"\n## 4. Quarantine\n\n{len(quarantined)} records are quarantined; reasons: {reasons}. Empty texts are "
          "quarantined at ingestion as `empty_review_text` and never sent to a model.\n"]
    return "\n".join(L)
